### ISSUE TITLE
Add way to enumerate through settings

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/SettingsPlugin#10]
### Feature Request

Would need to enumerate through keys and values.

API:

IDictionary<string, object> GetAll(string fileName = null);

_Copied from original issue: jamesmontemagno/Xamarin.Plugins#87_

**Comment by AndreiMisiukevich** [comment]
Maybe it would be redundant feature..
I think, that everybody who want to achieve this functionality can create separate property for storing all used keys.

smth like 

```csharp

        public static List<string> AllKeys
        {
            get
            {
                var sourceString = AppSettings.GetValueOrDefault(nameof(AllKeys), string.Empty, "all_keys.txt");
                return sourceString?.Split(' ').ToList() ?? new List<string>();
            }
            set
            {
                var sb = new StringBuilder();
                foreach(var key in value ?? Enumerable.Empty<string>())
                {
                    sb.Append(key);
                    sb.Append(" ");
                }
                AppSettings.AddOrUpdateValue(nameof(AllKeys), sb.ToString(), "all_keys.txt");
            }
        }
```

And change this collection after creating/deleting any property.

So, if developer wants to enumerate through all pair, he can write smth like

```csharp
           foreach(var key in AllKeys)
            {
                var value = AppSettings.GetValueOrDefault(key);
            }
```

**Comment by Cheesebaron** [comment]
Saving the keys in one string in Settings will eventually lead to an exception, since there is a size limit on values on Android.

**Comment by jamesmontemagno** [comment]
^ Accurate

I am no longer adding any new features to this library as all work will go into Essentials.
