### ISSUE TITLE
Changing device system time to the past blocks settings properties to be set

### ISSUE THREAD

**Issue by bbl-Laobu** [jamesmontemagno/SettingsPlugin#105]
## Bug Information

Version Number of Plugin: 2.5.8
Device Tested On: N/A
Simulator Tested On: 8 & 8 (IOS 11.1)
Version of VS: 7.2.2 BUILD 11 FOR MAC
Version of Xamarin: 2.4.0.282
Versions of other things you are using: N/A

### Steps to reproduce the Behavior
1. Create an app that sets a bool setting to 'true' and displays it in the application output
2. Run app on a IOS simulator device (ex iPhone 8) and verify the bool setting output shows 'true'
3. Manually set the system time to a time in the past (ex -6h). DO NOT use timezone but change time literally by changing the clock
4. Close simulator device so next time it starts the new time is displayed correctly on the device
5. Set bool to 'false' in code
6. Run app on the same IOS simulator Device (in our case iPhone 8)
7. Check console and notice that the bool setting output is still 'true' (should be false) 

### Expected Behavior
Setting the system time should have no impact on the correct running of the plugin

### Actual Behavior
Setting the system time to the past stops the plugin from properly setting its settings. 
NOTE: changing time by timezone does NOT create this bug.  

### Code snippet
N/A

### Screenshots
N/A

**Comment by jamesmontemagno** [comment]
I just make standard calls so would be an iOS bug if so
