### ISSUE TITLE
No support for android wear

### ISSUE THREAD

**Issue by kevingoos** [jamesmontemagno/SettingsPlugin#106]
I was testing the settings plugin on android wear, but no luck. There is no support for android wear included?

**Comment by jamesmontemagno** [comment]
Android wear is just an android app, so would work the same there as long as the API is provided. Since you didn't provide much information as to what happened not sure how to help here so please fill in more information.

**Comment by kevingoos** [comment]
Yea srry for not giving enough information. The problem that I am heaving on wear is as followed.

I use the following code to get to the settings (same as in the documentation)
```
private static ISettings AppSettings
{
    get
    {
        if (CrossSettings.IsSupported)
            return CrossSettings.Current;
        return null; // or your custom implementation 
    }
}
```

**On an normal android phone this works perfectly, but on an android wear device this will give back null instead.**

I can create/include a sample if this helps?

**Comment by jamesmontemagno** [comment]
Did you install the NuGet into your Wear app?

**Comment by kevingoos** [comment]
@jamesmontemagno Srry for my late reaction, yes I did install nuget in it. I installed the package from the nuget SettingsPlugin. Xam.Plugins.Settings

**Comment by prashantvc** [comment]
@kevingoos could you share a test project demonstrating this problem? It will help us to troubleshoot the issue
