### ISSUE TITLE
Cannot save settings value in iOS with Xamarin Live Player

### ISSUE THREAD

**Issue by merokoshiro** [jamesmontemagno/SettingsPlugin#107]
## Bug Information

Version Number of Plugin: 3.1.1
Device Tested On: iPhone 6s (iOS 11.1.2) with Xamarin Live Player
Simulator Tested On:
Version of VS: 15.4.5
Version of Xamarin: Xamarin.Forms 2.5.0.91635
Versions of other things you are using: 

### Steps to reproduce the Behavior
Save selected value from listview in settings

### Expected Behavior
Save the value in settings

### Actual Behavior
Crashes on `AppSettings.AddOrUpdateValue("App_selected_currency", currency.Code);` with error `Don't know to add `1` and `9` (System.Int64) (NInterpretException)`

### Code snippet
` AppSettings.AddOrUpdateValue("App_selected_currency", currency.Code);`

### Screenshots
![exception](https://user-images.githubusercontent.com/34065683/33382550-b9119878-d529-11e7-9e4e-70ffd9322803.jpg)

**Comment by jamesmontemagno** [comment]
Please file a bug for the live player at:  https://aka.ms/live-player-report-issue.

Please ensure you have the latest iOS version via Test Flight: https://aka.ms/live-player-alpha
