### ISSUE TITLE
Settings: AddOrUpdateValue always returns true (Android)

### ISSUE THREAD

**Issue by mrbelk** [jamesmontemagno/SettingsPlugin#11]
## Bug

Version Number of Plugin: 2.1.0
Device Tested On: 
Simulator Tested On: Nexus 4 (KitKat)
### Expected Behavior

Should only return true if the setting value was added or was actually different than the previous value
### Actual Behavior

Always returns true
### Steps to reproduce the Behavior

update a settings value that already exists and observe the return value of AddOrUpdate.

**Comment by jamesmontemagno** [comment]
It does not evaluate a change in the value, only if successful.
