### ISSUE TITLE
Question - Signing error on Plugin.Settings.Abstractions.dll & Plugin.Settings.dll

### ISSUE THREAD

**Issue by bmanners** [jamesmontemagno/SettingsPlugin#117]
I am attempting to make use of the settings plugin in a cross platform solution that includes a WPF application. If i try to publish the application i get a signing error on the above 2 files.

error MSB3188: Assembly 'C:\Users\brett.TMTROV\.nuget\packages\xam.plugins.settings\3.1.1\lib\net45\Plugin.Settings.dll' must be strong signed in order to be marked as a prerequisite.

Not sure if this is a problem with my solution or the setting plugin hence the question tag..

Brett

**Comment by jamesmontemagno** [comment]
I do not sight any of my libraries.
If you need:
https://github.com/dsplaisted/strongnamer
