### ISSUE TITLE
Missing String Name(s)

### ISSUE THREAD

**Issue by netsrotr** [jamesmontemagno/SettingsPlugin#12]
## Bug

Version Number of Plugin: 2.1
Device Tested On: Portable (Win)
### Expected Behavior

Abstraction.dll and Settings.dll with strong names
### Actual Behavior

No strong names. Our projects require strong names, so all references DLLs.

**Comment by jamesmontemagno** [comment]
Take a look at strong namer: https://github.com/dsplaisted/strongnamer

I do not plan on strong naming any of my libraries.
