### ISSUE TITLE
Settings are missing when app is removed from background

### ISSUE THREAD

**Issue by vhugogarcia** [jamesmontemagno/SettingsPlugin#121]
On Xamarin.Forms Android (5.1,6.0,7.0) When saving the information, it works great. However, if you close the app and clear the Android stack of apps running on background the settings values are missing.

Note: On iOS it works very good.

Plugin version 3.1.1

Any idea what the issue could be?

Regards,
Victor

**Comment by jamesmontemagno** [comment]
All values are store immediately into shared preferences. Has worked perfect for 6 years with 1+ million installs here... can you share code at all that you are using?

Is it redeploy via debugging? Perhaps you have clear values on?

**Comment by vhugogarcia** [comment]
Hello @jamesmontemagno , that is also why it is really weird that is not working for me on Android only.

This is the code I'm using:
`namespace Demo.Helpers
{
    public static class Settings
    {
        private const string RememberUserKey = "RU_Key_1";
        private const string UserPasswordKey = "UP_Key_1";
        private const string UserEmailKey = "UE_Key_1";
        
        private static readonly bool RememberUserDefault = false;
        private static readonly string UserPassworDefault = string.Empty;
        private static readonly string UserEmailDefault = string.Empty;
        
        private static ISettings AppSettings
        {
            get {  return CrossSettings.Current; }
        }

        public static bool RememberUser
        {
            get { return AppSettings.GetValueOrDefault(RememberUserKey, RememberUserDefault); }
            set { AppSettings.AddOrUpdateValue(RememberUserKey, value); }
        }

        public static string UserPassword
        {
            get { return AppSettings.GetValueOrDefault(UserPasswordKey, UserPassworDefault);}
            set { AppSettings.AddOrUpdateValue(UserPasswordKey, value);}
        }

        public static string UserEmail
        {
            get { return AppSettings.GetValueOrDefault(UserEmailKey, UserEmailDefault); }
            set { AppSettings.AddOrUpdateValue(UserEmailKey, value); }
        }

    }
}`

However, when I retrieve the values on the ViewModel RememberMe is always false:
`
ObjectUser.RememberUser = Settings.RememberUser;
            ObjectUser.Email = RememberUser ? Settings.UserEmail : string.Empty;
            ObjectUser.Password = RememberUser ? Settings.UserPassword : string.Empty;
`

**Comment by jamesmontemagno** [comment]
[App1.zip](https://github.com/jamesmontemagno/SettingsPlugin/files/1839551/App1.zip)

This code works absolutely perfect. No issues at all.
