### ISSUE TITLE
Settings.bundle on iOS sample

### ISSUE THREAD

**Issue by jrummell** [jamesmontemagno/SettingsPlugin#13]
Please fill out either the bug or feature request section and remove whatever section you are not using.
## Bug

Version Number of Plugin:
Device Tested On: iOS
Simulator Tested On:
### Expected Behavior

Read/write to Settings.bundle/Root.plist, edit from iOS Settings app
### Actual Behavior

Settings are not displayed in iOS Settings app
## Feature Request:

Is this designed to work with Settings.bundle/Root.plist in iOS? If so, can you provide and example?

**Comment by jamesmontemagno** [comment]
Yup, you should be able to: https://github.com/jamesmontemagno/Xamarin.Plugins/issues/311

it uses NSUserDefaults

**Comment by jrummell** [comment]
It totally does work. There must be something wrong with my project. I have to remove the iOS app and data every time I update the build, then it shows up. Thanks!
