### ISSUE TITLE
Unable to Update to Version 4.0.0.7 using VS Nuget Manager

### ISSUE THREAD

**Issue by Hunv** [jamesmontemagno/SettingsPlugin#131]
## Bug Information
Version Number of Plugin: 
Device Tested On: Google Pixel 2, Medion Lifetab
Simulator Tested On: VS Emulator
Version of VS: 2017
Version of Xamarin: 3.0

### Steps to reproduce the Behavior
Update to v4.0.0.7 via Nuget Manager of Visual Studio.

### Expected Behavior
Update will be performed

### Actual Behavior
You will get this error Message:
Failed to add reference. The package 'Xam.Plugins.Settings' tried to add a framework reference to 'System.Collections' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Btw: This is the Same for your package "Plugin.CurrentActivity" with Version 2.1.0.1

### Code snippet
n/a

### Screenshots
n/a

**Comment by jamesmontemagno** [comment]
Rolled this back btw

**Comment by nok3250** [comment]
4.0.0.7 is still on Nuget and this issue still reproduces
