### ISSUE TITLE
Migrating from Packages.config to Project references compability issue?

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/SettingsPlugin#133]
I want to migrate my android project using project references but when I right click on the packages.config file and say migrate, it shows warning for settings and currentactivity plugin? do you know what issue might I experience if I migrate it? should I ignore this message? 

![image](https://user-images.githubusercontent.com/10422347/40235670-42d6f2b8-5aab-11e8-9c70-8b25c29e15cd.png)

**Comment by jamesmontemagno** [comment]
yeah, that is fine, it will remove your settings.cs and mainapplication.cs so maybe copy those first :)
