### ISSUE TITLE
Namespace name 'Extensions' does not exist

### ISSUE THREAD

**Issue by joakimmag** [jamesmontemagno/SettingsPlugin#134]
Getting this error. Have re-installed, cleaned, re-built project.

## Bug Information

Version Number of Plugin: 3.1.1
Device Tested On: Not tested, can't build.
Simulator Tested On:
Version of VS: 15.7.2
Version of Xamarin: 3.0.0.482510
Versions of other things you are using:

### Steps to reproduce the Behavior

1. Install Xam.Plugin.Settings in all projects
2. Add using directive `using Plugin.Settings.Abstractions.Extensions;`
3. Add code to use auto-key detection
4. Debug project

### Expected Behavior

No IntelliSense or compiler error.

### Actual Behavior

Build error: error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Plugin.Settings.Abstractions' (are you missing an assembly reference?)

### Code snippet

    using Plugin.Settings.Abstractions.Extensions;

    private static ISettings AppSettings => CrossSettings.Current;

    public static bool IsAppInitialized
    {
        get => AppSettings.GetValueOrDefault();
        set => AppSettings.AddOrUpdateValue(value);
    }

### Screenshots

![screenshot_1](https://user-images.githubusercontent.com/28116634/40358834-e4967458-5dc0-11e8-90b6-62b6c85b4591.png)

**Comment by AndreiMisiukevich** [comment]
Hi @wireless-r 
Unfortunately, this feature is available only from beta channel..
Try to install the last pre-release package (https://www.nuget.org/packages/Xam.Plugins.Settings/4.0.0.10-beta)

But I hope, @jamesmontemagno will release stable version soon.
