### ISSUE TITLE
Settings on amazon fire remains if deleting app data or reinstalling the app

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/SettingsPlugin#137]
**Failure to fill out this information will result in this issue being closed.**

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

 If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

I have just tested some settings of my app on Amazon fire device. Something interesting happens if I delete app data or uninstall the app and reinstall, settings are restored from previous state. It is probably some thing specific to amazon devices but can you imagine what could be the reason?

Version Number of Plugin: latest
Device Tested On: amazon fire hd 8
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 3.1
Versions of other things you are using:

### Steps to reproduce the Behavior
Install app on the device with some settings 
### Expected Behavior
Delete app data or uninstall app, settings should be removed also
### Actual Behavior
Settings remains

**Comment by jamesmontemagno** [comment]
It is possible as this is the behavior on newer android devices: https://developer.android.com/guide/topics/data/autobackup
