### ISSUE TITLE
Compatiablity with .net core applications

### ISSUE THREAD

**Issue by squinn7** [jamesmontemagno/SettingsPlugin#139]
We are in the process of migrating our libraries to .net 2.0 and this caused an issue in our test project as it no longer functions in our unit tests because we changed the test project to a .net core(2.0) console application. Right now, the settings plugin will throw a not implemented exception when run in our .net core console app. I am not sure if we are doing something wrong or if it isn't currently compatible. 

Our approach is to see if we can fix the plugin or we will migrate the test project back to net framework project with a target of 4.7.x

Let me know if you need more info.

Thanks

**Comment by jamesmontemagno** [comment]
Install the 3.2.0 or 4.0.0 beta and will work out nicely for you :)

**Comment by squinn7** [comment]
Worked great, thanks for the quick response.
