### ISSUE TITLE
Error message on asp.net core console app

### ISSUE THREAD

**Issue by okhosting** [jamesmontemagno/SettingsPlugin#140]
**Failure to fill out this information will result in this issue being closed.**

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

 If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.1.1
Device Tested On: Windows7
Simulator Tested On: NetCore console app
Version of VS: 15.8.2
Version of Xamarin:integrated with VS
Versions of other things you are using:

### Steps to reproduce the Behavior
1- Create a new ASP.NET Core console app
2- Add nuget Xam.Plugins.Settings
3- At the ver start run: Plugin.Settings.CrossSettings.Current.OpenAppSettings();

### Expected Behavior

No error message

### Actual Behavior
Exception thrown:
This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.'

### Code snippet

Plugin.Settings.CrossSettings.Current.OpenAppSettings();

**Comment by jamesmontemagno** [comment]
Asp.net core you need the 4.0 beta

**Comment by okhosting** [comment]
Thanks James! sorry about the trouble!

**Comment by jamesmontemagno** [comment]
it is my fault :) i need to update it so it isn't confusing
