### ISSUE TITLE
Is this library deprecated with  Xamarin.Essentials/preferences ?

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/SettingsPlugin#143]
If this is the case, it seems that usage is totally changed. now [preferences ](https://docs.microsoft.com/en-us/xamarin/essentials/preferences)uses akavache style while settings plugin was simply assigning values like below. thats why I prefer to use settings library for simple types while akavache for object types. 

>     Settings.LoginAccessToken = token;

I found preferences library similar to securestorage and akavache. i just wanted to share my opinion.  Not sure maybe i should create this issue in xamarin essentials? please feel free to move there or close it :)

**Comment by jamesmontemagno** [comment]
Preferences in Xamarin.Essentials is a drop in replacement for the Settings Plugin...

Take the code above^
```csharp
public static string LoginAccessToken 
{
    get =>  AppSettings.GetValueOrDefault(SettingsKey, SettingsDefault);
    set => AppSettings.AddOrUpdateValue(SettingsKey, value);
}
```

With Xamarin.Essentials it is literally:

```csharp
public static string LoginAccessToken 
{
    get =>  Preferences.Get(SettingsKey, SettingsDefault);
    set => Preferences.Set(SettingsKey, value);
}
```

They even store them in the same location by default so you can easily replace them. 

See my guide: https://montemagno.com/upgrading-from-plugins-to-xamarin-essentials/
