### ISSUE TITLE
[Tizen TV] Save/read fail

### ISSUE THREAD

**Issue by cansado2930** [jamesmontemagno/SettingsPlugin#144]
Hi,
I have developing a Xamarin forms app for Tizen TV and I have tried to read/save a preference as I do on Android, Windows, ios… but It faults. 
Could you tell me if I have to do something in order to it works?
Thank you

**Comment by jamesmontemagno** [comment]
Tizen is supported in 4.0+ beta

**Comment by cansado2930** [comment]
Thank you very much. It was the problem.
I wish you a happy new year
