### ISSUE TITLE
The values ​​are encrypted?

### ISSUE THREAD

**Issue by INHack20** [jamesmontemagno/SettingsPlugin#145]
I want to store basic information with the library but sensitive, is it safe to use it or should I look for an alternative? Thank you

**Comment by jamesmontemagno** [comment]
Nope, you will want to put them in Secure Storage: https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage

**Comment by INHack20** [comment]
Perhaps a function could be implemented that allows saving some flat values by default and other encrypted values when necessary.

Excellent library! Thank you!

**Comment by jamesmontemagno** [comment]
Settings/Preferences are not encrypted.... Secure Storage puts it into keychain and secure area. They are very different APIs
