### ISSUE TITLE
Unhandled Exception Android Emulator

### ISSUE THREAD

**Issue by ivanrlg** [jamesmontemagno/SettingsPlugin#150]
**Failure to fill out this information will result in this issue being closed.**

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

 If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.1.1
Device Tested On: UWP, Android
Simulator Tested On: Android Emulator
Version of VS: 15.9.7
Version of Xamarin: 4.12.3.80
Versions of other things you are using:

### Steps to reproduce the Behavior
When you start the application on Android Emulator

### Actual Behavior

 Java.Lang.ClassCastException: 
Timeout exceeded getting exception details

### Code snippet
```
        public static bool IsRemembered
        {
            get
            {
                **return AppSettings.GetValueOrDefault(isRemembered, booleanDefault);**
            }
            set
            {
                AppSettings.AddOrUpdateValue(isRemembered, value);
            }
        }
```

**Comment by jamesmontemagno** [comment]
What is "isRemembered"

**Comment by ivanrlg** [comment]
> What is "isRemembered"

I use it if a user wants to remember that did login in the device so that in a future beginning the system does not request the credentials again.

      `private const string isRemembered = "IsRemembered";`

Currently works on an android physical device and in uwp

**Comment by jamesmontemagno** [comment]
Did you accidentally set it to something besides a a boolean on the emualtor? perhaps try to delete the app and try again? I jsut tested out the code in my emulator and worked great:

![image](https://user-images.githubusercontent.com/1676321/53211318-9b48a600-35f5-11e9-99a8-2ff68bd9b8dd.png)

**Comment by ivanrlg** [comment]
Thank you very much for your time, I had not tried to uninstall the emulator application, that was the solution to the exception that occurred.
