### ISSUE TITLE
[Question] Xamarin essentials and .Net 4.5

### ISSUE THREAD

**Issue by VladislavAntonyuk** [jamesmontemagno/SettingsPlugin#151]
Xamarin Essentials supports only Android, iOS and UWP. but your plugin supports also macOS and .Net 4.5. Is it save for me to migrate to Xamarin Essentials?

**Comment by jamesmontemagno** [comment]
It depends what you need to support. There is an open issue for additional platforms, but you shouldn't rely on that as there is no guarantee they will get officially supported.

https://github.com/xamarin/Essentials/issues/662

I will not stop supporting my plugins, but probably will not add new features to them.

**Comment by VladislavAntonyuk** [comment]
I wanna save settings to file in isolatedstorage as it works now in this plugin
