### ISSUE TITLE
Settings Plugin not working with Visual Studio 2019

### ISSUE THREAD

**Issue by davidbuckleyni** [jamesmontemagno/SettingsPlugin#153]
Hi James big fan of your work but for the life of me I cannot get the settings plugin to work at all

![](https://i.imgur.com/l1pLszQ.png)

As you can see from above there is an error I am using latest xam forms as you can see and .net standard 2.0 please can you help me out?

I was wanting to use and share the login information to the app through it but prehaps I should be using the finger print reader also any ideas how one would do that in xam forms and store the username and password in the keygen.

**Comment by jamesmontemagno** [comment]
Maybe uninstall and re-install. works for me here...
