### ISSUE TITLE
Can I have more than one information stored ?

### ISSUE THREAD

**Issue by lepetitpaco** [jamesmontemagno/SettingsPlugin#154]
When I'm saving a second variable, the first one also takes the value.

If I save string_one first, string one and two will have the same content, 
but if I set string_two later, the value of both string_one and string_two will be the same.

How to have two separate values ?

`

        private static ISettings AppSettings =>
            CrossSettings.Current;

        public static string String_one
        {
            get => AppSettings.GetValueOrDefault(nameof(String_one), string.Empty);
            set => AppSettings.AddOrUpdateValue(nameof(String_one), value);
        }

        public static string String_two
        {
            get => AppSettings.GetValueOrDefault(nameof(String_two), string.Empty);
            set => AppSettings.AddOrUpdateValue(nameof(String_two), value);
        }

`

**Comment by jamesmontemagno** [comment]
This looks valid and would work as intended.

**Comment by jamesmontemagno** [comment]
I tested it and works perfect for me, the name is the key.
