### ISSUE TITLE
Settings Key shared across other applications

### ISSUE THREAD

**Issue by LeoJHarris** [jamesmontemagno/SettingsPlugin#155]
Hi all,

This is a quick question that made me wonder, if two applications have the same key in their settings classes i.e. **TheKey**

```csharp
AppSettings.GetValueOrDefault(TheKey, _settingsDefault);
```

Would it be possible that those two applications are sharing the same object when they get it from AppSettings or would this be isolated to each app, because I have two apps that have share the same Key and I'm thinking I might need to change those key names?

**Comment by jamesmontemagno** [comment]
Apps are sandboxed and the data is persisted to the app itself. Android used to have a concept of world readable, but that is a huge gap in security and they mostly don't support that. 

On iOS you can do it between your bundled apps such as phone and watch with a group.
