### ISSUE TITLE
Nuget packages 4.0.0.7 seems to have been recently unlisted

### ISSUE THREAD

**Issue by cosminstirbu** [jamesmontemagno/SettingsPlugin#156]
Hello,

We've bumped to version 4.0.0.7 back in 12th of June to 2019 and now Nuget restore complaints that it can't find the version.

https://www.nuget.org/packages/Xam.Plugins.Settings/4.0.0.7 says that "The owner has unlisted this package. This could mean that the package is deprecated or shouldn't be used anymore."

Not sure I understand why.

Regards,
Cosmin

**Comment by jamesmontemagno** [comment]
Yes, 4 has never left beta.
