### ISSUE TITLE
Using a DateTime Type Results in a UTC Return.

### ISSUE THREAD

**Issue by maxmin88** [jamesmontemagno/SettingsPlugin#157]
When I save a local DateTime to a DateTime setting it always returns a UTC time.  On all my retrievals of a DateTime Setting I have to add .ToLocalTime() to get my local time back

## Bug Information

Version Number of Plugin:  3.1.1
Device Tested On: OnePlus 6T
Simulator Tested On:
Version of VS: 16.3.4
Version of Xamarin: Forms 4.2.0.815419
Versions of other things you are using:

### Steps to reproduce the Behavior
Settings.LastDateRetrieval = DateTime.Now;
var datetime = Settings.LastDateRetrieval;           //returns UTC time
### Expected Behavior
expect it to return the DateTime value I put in
### Actual Behavior
 returns UTC time
### Code snippet
  public static class Settings
   {
      private static Plugin.Settings.Abstractions.ISettings AppSettings =>
                                   Plugin.Settings.CrossSettings.Current;
       public static DateTime LastDateRetrieval
      {
         get { return AppSettings.GetValueOrDefault(nameof(LastDateRetrieval), DateTime.MinValue); }
         set { AppSettings.AddOrUpdateValue(nameof(LastDateRetrieval), value); }
      }
}

Settings.LastDateRetrieval = DateTime.Now;
var datetime = Settings.LastDateRetrieval;           //returns UTC time

**Comment by jamesmontemagno** [comment]
Yes, this is by design.

**Comment by maxmin88** [comment]
That wouldn’t be my preference. But thanks for the reply.

Robert Twickler

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
