### ISSUE TITLE
does the settingsPlugin support for EMM providers ?

### ISSUE THREAD

**Issue by chathumdavton** [jamesmontemagno/SettingsPlugin#159]
As per my knowledge most EMM providers support the appconfig standard and in order for the xamarin apps to receive configuration from a EMM provider we need to communicate with the platforms separately.
**ios**
NSUserDefaults.StandardUserDefaults.DictionaryForKey("com.apple.configuration.managed")
**android**
register a receiver for the "ActionApplicationRestrictionsChanged" broadcast actions and then read and apply restrictions using RestrictionsManager.ApplicationRestrictions

Is this functionality supported by the settingsPlugin ? If not what is the best way for me to use the settingsplugin and achieve the above functionality ?

**Comment by jamesmontemagno** [comment]
We don't support Dictionary on iOS, however do support group names.

For Android there is no support for the RestrcitionManager at all.

This is super easy code to write and manage so I would just do that yourself.
