### ISSUE TITLE
System.NotImplementedException

### ISSUE THREAD

**Issue by ghost** [jamesmontemagno/SettingsPlugin#16]
Please fill out either the bug or feature request section and remove whatever section you are not using.
## Bug

Version Number of Plugin: 2.1.0
Device Tested On:
Simulator Tested On: Android emulator in Visual Studio

Code is breaking when trying to set a value. The error returned is...

System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

This breaks at the following point:

return CrossSettings.Current;

The NuGet package is installed in the project at the PCL solution level and also on both Droid and iOS.

-Dave

**Comment by tallkid10** [comment]
I also just encountered this error doing the same thing dave mentioned.

**Comment by tallkid10** [comment]
@davebanthorpe  I was able to clean the solution, rebuild, and it worked as mentioned by Ivan here:
https://forums.xamarin.com/discussion/comment/216147/#Comment_216147
