### ISSUE TITLE
Migration to PackageReference

### ISSUE THREAD

**Issue by wegascee** [jamesmontemagno/SettingsPlugin#160]
I tried the wizard [Migrate from packages.config to PackageReference](https://docs.microsoft.com/de-de/nuget/consume-packages/migrate-packages-config-to-package-reference) in my project and get a compatibility issue. Is the wizard wrong or is there an issue with the plugin?

## Bug Information

Version Number of Plugin: Xam.Plugins.Settings 3.1.1
Device Tested On: Samsung Galaxy Tab Active2
Simulator Tested On: -
Version of VS: 15.9.14
Version of Xamarin: 4.12.3.83
Versions of other things you are using: -

### Steps to reproduce the Behavior
1. You need a project which you want to move to .NETStandard2.0
2.  PCL has already been converted. Now you use the wizard *Migrate packages.config to PackageReference...* from e.g. an Android project with a `packages.config`
3. Make the conversion and review any package compatibility issues

### Expected Behavior
Migration to PackageReference works without compatibility issues

### Actual Behavior
>Assets in `content` are not copied into the project and project code that depends on the presence of those assets requires refactoring.

**Comment by jamesmontemagno** [comment]
No issue, that is fine. In the older 3.1.1 there is a file that is put in place, however in newer betas I don't even use it anymore.
