### ISSUE TITLE
Migration to Xamarin Essentials

### ISSUE THREAD

**Issue by ndastur** [jamesmontemagno/SettingsPlugin#161]
This package has been replaced by Essentials. As far as I can tell the essentials implementation is exactly the same. I'm looking to swap out this plugin. Initial test on iOS 13.4 and Android 9 show that settings retrieved with the Essentials methods get any values previously stored by this plugin.

@jamesmontemagno I wonder if you had done any tests and if you knew of any reasons why a direct swap from one to the other shouldn't work. For example with different OS versions.

If they are directly compatible then maybe a note on the README saying Essentials can be swapped in might be of benefit.

**Comment by jamesmontemagno** [comment]
They store in the same place :) https://montemagno.com/upgrading-from-plugins-to-xamarin-essentials/
