### ISSUE TITLE
I don't see how to use? 

### ISSUE THREAD

**Issue by sergeibystrov** [jamesmontemagno/SettingsPlugin#167]
Please I need to see an example app of how to implement. There's none except for the test which gives no detailed use about implementation

**Comment by jamesmontemagno** [comment]
There is documentation: https://jamesmontemagno.github.io/SettingsPlugin/

But you should use https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/storage/preferences

**Comment by sergeibystrov** [comment]
If I should use preference and he/she disable the app then rentable it by
freezing the app, I'm sure the preference won't hold any value anymore

**Comment by jamesmontemagno** [comment]
preference are saved and stored across app starts and based on OS even uninstall.
