### ISSUE TITLE
[Feature Request] Add option to launch settings page for app

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/SettingsPlugin#2]
_From @jamesmontemagno on May 27, 2016 17:43_

This is a 
- [x] Feature Request

Which plugin does this impact:
- [x] Settings
### Request

Would be nice to have 1 cross platform call to launch the settings page for the different platforms. iOS can launch into the app specifically, and Android is an intent.

_Copied from original issue: jamesmontemagno/Xamarin.Plugins#317_

**Comment by Bartmax** [comment]
:+1: This would be great!!

**Comment by jamesmontemagno** [comment]
I actually include this into: https://github.com/jamesmontemagno/PermissionsPlugin

So I will probably close this for now. Could be worth adding in the future though.

**Comment by Bartmax** [comment]
What's the motivation to have the appsettings open on a `permission` plugin instead of `settings` plugin?
sounds strange at least, in my current app, I don't use/need a permission plugin but I do use the settings plugin and do open the system settings app.

**Comment by jamesmontemagno** [comment]
I guess I only ever needed to open it from the permission plugin...
hmmm I can probably just add the same code lol :)

**Comment by jamesmontemagno** [comment]
I'll put it in v 3 :)

**Comment by Bartmax** [comment]
thank you :)

**Comment by jamesmontemagno** [comment]
Any info if there is a UWP way to do it... figure I would ask before I research.

**Comment by jamesmontemagno** [comment]
Implemented in 3.1.0-beta
