### ISSUE TITLE
Support for .NETStandard?

### ISSUE THREAD

**Issue by FroggieFrog** [jamesmontemagno/SettingsPlugin#22]
## Feature Request:

Ist it possible to support .NetStandard? It is written everywhere to use .NetStandard instead of PCLs, but this plugin is not compatible (yet).

Package Manager console:
Package Xam.Plugins.Settings 2.5.1 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Xam.Plugins.Settings 2.5.1 supports:
- monoandroid10 (MonoAndroid,Version=v1.0)
- net45 (.NETFramework,Version=v4.5)
- portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
- uap10 (UAP,Version=v1.0)
- win8 (Windows,Version=v8.0)
- wp8 (WindowsPhone,Version=v8.0)
- wpa81 (WindowsPhoneApp,Version=v8.1)
- xamarinios10 (Xamarin.iOS,Version=v1.0)
  One or more packages are incompatible with .NETStandard,Version=v1.4.

See: [https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) (section: As a library author, what should I do now?)

**Comment by InquisitorJax** [comment]
try adding PCL Compatibility in your .NET Standard lib json file.
See [here](https://xamarinhelp.com/dot-net-standard-pcl-xamarin-forms/)
Add this: "imports": "portable-net45+win8+wpa81+wp8"

Note that I removed the square [ ] brackets that are used in the linked article.

**Comment by FroggieFrog** [comment]
When I add the imports-section, then I can use the the plugin. But it would be better/simpler if it "just works". :-)

My project.json (for completeness):
`{
  "supports": {},
  "dependencies": {
    "Microsoft.NETCore.Portable.Compatibility": "1.0.1",
    "NETStandard.Library": "1.6.0",
    "Newtonsoft.Json": "9.0.1",
    "Xam.Plugin.Connectivity": "2.2.12",
    "Xam.Plugins.Settings": "2.5.1"
  },
  "frameworks": {
    "netstandard1.4": {
      "imports": "portable-net45+win8+wp8+wpa81"
    }
  }
}`

**Comment by InquisitorJax** [comment]
maybe close the issue since it's solved?

**Comment by jamesmontemagno** [comment]
I will add full .NET standard support when 2.0 comes out soon.
