### ISSUE TITLE
DateTime property Always fallback to UTC

### ISSUE THREAD

**Issue by xalikoutis** [jamesmontemagno/SettingsPlugin#29]
## Bug 

Version Number of Plugin: 2.5.1
Device Tested On: Samsung Tab S2

If i create a property with type DateTime Always fallback to UTC even if it has a default value like this

```
 private const string ExpireTokenDateKey = "expiretokendate_key";
private static readonly DateTime ExpireTokenDateDefault = new DateTime(1980,10,19,12,12,12, DateTimeKind.Local);
```
Then if i do
`Settings.ExpireTokenDate = DateTime.Now.AddSeconds(_authenticationResult.ExpiresIn);`
Settings.ExpireTokenDate is in UTC

**Comment by jamesmontemagno** [comment]
Ate times are always stored in UTC. This is as designed.
