### ISSUE TITLE
[Bug]/[Feature Request] UWP is limited to 8K characters

### ISSUE THREAD

**Issue by rjcollingham** [jamesmontemagno/SettingsPlugin#30]
## Feature Request:
Saving a string is limited to 8K in UWP. This is not the case for iOS and Android.

Any way of avoiding this, or changing the implementation to overcome this limitation?

Thanks

**Comment by jamesmontemagno** [comment]
It would be a limitation of the platform. Android also has similar limitations.

**Comment by jamesmontemagno** [comment]
You should not be saving complex objects into settings, which is usually when this happens. Save a file do disk with PCL Storage or into a database.
