### ISSUE TITLE
Android lose settings

### ISSUE THREAD

**Issue by scinfu** [jamesmontemagno/SettingsPlugin#32]
Version Number of Plugin: 2.5.1.0 and pre
Device Tested On: Nexus s , nexus 5 , nexus 7 and other non google device.

In Android frequently but randomly settings losses.
To try to reproduce the bug you can rebuild but it happens also with a normal build signed and not .

**Comment by jamesmontemagno** [comment]
Would need a reproducible bug and sample as I have never seen this. You would see it between uninstalls and re-installs and based on Xamarin settings could be between deploys for debugging.

Open new bug if you have a sample of it happening
