### ISSUE TITLE
Remove app but Settings are remaining

### ISSUE THREAD

**Issue by erossini** [jamesmontemagno/SettingsPlugin#33]
## Settings are remaining after an app is deleted

Version Number of Plugin: 2.5.1.0
Device Tested On: iPad Pro

### Expected Behavior
If I cancel an app, all settings are deleted

### Actual Behavior
If I cancel an app and I reinstall it, I have all my old settings.
For example I save in settings, if an app is started for the first time. If yes I create some demo data. 

### Steps to reproduce the Behavior
Delete and app and reinstall it.

**Comment by jamesmontemagno** [comment]
Are you testing on device or simulator?  See: http://stackoverflow.com/questions/24985825/nsuserdefaults-not-cleared-after-app-uninstall-on-simulator as it may not be removed from Simulator.

**Comment by Thijmen** [comment]
I have this issue too. Using a simple string. I have no clue how to provide more information.

**Comment by awatertrevi** [comment]
Same here, using the latest version of the plugin (only on Android though).

**Comment by jamesmontemagno** [comment]
On Android you would have to turn off auto backup: https://developer.android.com/guide/topics/data/autobackup

**Comment by awatertrevi** [comment]
Ah that explains it! Thanks @jamesmontemagno!
