### ISSUE TITLE
[Feature Request] Add support for App.Settings (Configuration Manager)

### ISSUE THREAD

**Issue by ravensorb** [jamesmontemagno/SettingsPlugin#34]

**Comment by jamesmontemagno** [comment]
I am not sure what you are asking here. Can you fill in more information.

**Comment by ravensorb** [comment]
Sorry about that :)  Basically add support for System.Configuration.ConfigurationManager -- this is the Full .NET Configuration manager for things like app.config and web.config appSettings sections.

**Comment by jamesmontemagno** [comment]
out of the scope for this project, thanks for the request and idea though.
