### ISSUE TITLE
Error occurred while trying to restore packages

### ISSUE THREAD

**Issue by wierzba3** [jamesmontemagno/SettingsPlugin#36]
I added this package to my portable project and it compiled fine but then I got a runtime error that said something about needing to reference the nuget package in the platform project (android in this case)

So I tried adding it to the android project, and now I get the following NuGet errors.
It appears that neither project can find the NuGet solution now?

Error		NuGet Package restore failed for project PatrolLiveApp.Droid: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to find version '2.5.1' of package 'Xam.Plugins.SettingsModel'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Xam.Plugins.SettingsModel.2.5.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'Xam.Plugins.SettingsModel.2.5.1' is not found on source 'https://api.nuget.org/v3/index.json'.
  http://nugets.vapolia.fr/nuget/: Package 'Xam.Plugins.SettingsModel.2.5.1' is not found on source 'http://nugets.vapolia.fr/nuget/'.

Error		NuGet Package restore failed for project PatrolLiveApp: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to find version '2.5.1' of package 'Xam.Plugins.SettingsModel'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Xam.Plugins.SettingsModel.2.5.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'Xam.Plugins.SettingsModel.2.5.1' is not found on source 'https://api.nuget.org/v3/index.json'.
  http://nugets.vapolia.fr/nuget/: Package 'Xam.Plugins.SettingsModel.2.5.1' is not found on source 'http://nugets.vapolia.fr/nuget/'.

## Bug 

Version Number of Plugin: 2.5.1
Device Tested On: Visual Studio 2015

**Comment by jamesmontemagno** [comment]
Seems like a nuget issue. Try to only select the nuget.org feed and try to restore it.

**Comment by wierzba3** [comment]
Wow. It was re-sharper's fault. I renamed my old Settings.cs so I could try out this plugin
It renamed the nuget package as well as the class references, hah.
So it was looking for "SettingsModel"  not "Settings"

**Comment by wierzba3** [comment]
apologies

**Comment by jamesmontemagno** [comment]
Ahhh good find. Yeah that is a tricky one, i just always keep it the Settings.cs although it should try to add a new one in there. It was always a big debate if I should add it or not. I like it personally.
