### ISSUE TITLE
System.NotImplemented 

### ISSUE THREAD

**Issue by wierzba3** [jamesmontemagno/SettingsPlugin#37]
I get this error when attempting to modify my Settings.cs
System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

I followed the instructions by adding the nuget package to my portable project. What then does error indicate?

**Comment by wierzba3** [comment]
I realize this may be user error, is there a way I can post this as a discussion instead of an issue?

**Comment by jamesmontemagno** [comment]
Issues are fine and I can respond. You just need to install the NuGet into ALL projects including platform specific ones.

**Comment by wierzba3** [comment]
Well I had installed it on the portable and android (I was executing the android one).
I went ahead and added it to every project (I have 6, a PCL, Android, iOS, and also a common library for each of those that we share accross multiple mobile projects)

Still getting same error above...

**Comment by jamesmontemagno** [comment]
Make sure to do a clean and re-build on everything. Might just be some build  error of something being cached around. Else remove and re-add in.

**Comment by wierzba3** [comment]
Tried both and still no luck

**Comment by jamesmontemagno** [comment]
Do you have a small sample I can look at?

**Comment by wierzba3** [comment]
Yeah

Here is my Settings.cs https://gist.github.com/wierzba3/9236c379e4e0fa668e7a92046aa66f34

And in my App.xaml.cs constructor, where I do my setup, I call this
    PatrolLiveApp.Helpers.Settings.DeviceId = 123;
and this is what causes the crash described above.

(This is all in my Portable project)
And as you know I added the NuGet package to all of my projects, tried a clean+rebuild, and re-adding NuGet package.

**Comment by jamesmontemagno** [comment]
I tested this out with a blank XAML xamarin.forms app and was not able to reproduce it. I have attached my project below. Maybe something is getting linked out.... not sure what your settings are, but I assume it is in debug mode so none.

**Comment by jamesmontemagno** [comment]
Actually this one:
[App2.zip](https://github.com/jamesmontemagno/SettingsPlugin/files/683026/App2.zip)

**Comment by wierzba3** [comment]
Hmm yes your sample works. Odd, I'm not sure what the difference is. I will compare the projects more closely

**Comment by jon-peel** [comment]
Hey, did you figure out what the issue was? I am getting the same problems.

**Comment by jamesmontemagno** [comment]
Upgrade all of the libraries and ensure that you clean and rebuild.

**Comment by jon-peel** [comment]
I did notice I had different versions. I think I ended up on 2.5
When trying version 3 I would get an error about mono.posix

**Comment by jamesmontemagno** [comment]
Most likely you are running into this: https://bugzilla.xamarin.com/show_bug.cgi?id=56787

which is very strange, not an issue with this library, with some tooling that appears to be fixed.
