### ISSUE TITLE
[Feature Request] It would be nice if we could list all the existing settings.

### ISSUE THREAD

**Issue by jonathanantoine** [jamesmontemagno/SettingsPlugin#39]
## Feature Request:
It would be nice if we could list all the existing settings. 
If we want to remove only some of them for instance.

`foreach (var kVp in CrossSettings.Current.Values)`
`{`
`    var key = kVp.Key;`
`    var value = kVp.Value;`
`}`

Thank you !

**Comment by Ingenator** [comment]
I need this one too!!

**Comment by jamesmontemagno** [comment]
Duplicate of #10
