### ISSUE TITLE
2.5.2.1 Android Double

### ISSUE THREAD

**Issue by ClausElmann** [jamesmontemagno/SettingsPlugin#41]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 
2.5.2.1 Android Double

```
double x = 1.5;
Settings.FontFactor = x;
var y = Settings.FontFactor; (returns 15, not 1,5)
```

**Comment by jamesmontemagno** [comment]
What does your: Settings.FontFactor code behind look like?

**Comment by ClausElmann** [comment]
This works in 2.5.1 - so I rolled back :-)
```
 public static double FontFactor
        {
            get
            {
                return AppSettings.GetValueOrDefault("fontFactor_" + Singleton.Instance.brugerID, (double)1);
            }
            set
            {
                AppSettings.AddOrUpdateValue("fontFactor_" + Singleton.Instance.brugerID, value);
            }
        }
```

**Comment by jamesmontemagno** [comment]
interesting... will investigate

**Comment by jamesmontemagno** [comment]
Sorry about that. Pushed out 2.5.3.0 and added Unit tests. Was an optimization in doubles and of course that small regression sorry.

**Comment by ClausElmann** [comment]
Thanks James
Real fan of all your hard work 👍
