### ISSUE TITLE
Color problem

### ISSUE THREAD

**Issue by erossini** [jamesmontemagno/SettingsPlugin#42]
In other my project this is working fine. FYI in this project I added a Acr.Geofences library.

## Bug 

Version Number of Plugin: 2.5.2.1
Device Tested On: Android 6
Simulator Tested On: Android 6

### Expected Behavior
Return a Color or ColorDefault

    private const string BoxColorWorkKey = "BoxColorWork_key";
    private static readonly Color BoxColorWorkDefault = Color.FromHex("#65A4BE");
    public static Color BoxColorWorkSettings
    {
        get
        {
            return AppSettings.GetValueOrDefault<Color>(BoxColorWorkKey, BoxColorWorkDefault);
        }
        set
        {
	    AppSettings.AddOrUpdateValue<Color>(BoxColorWorkKey, value);
        }
    }

### Actual Behavior
Exception

>   at Plugin.Settings.SettingsImplementation.GetValueOrDefaultCore[T] (Android.Content.ISharedPreferences sharedPreferences, System.String key, T defaultValue) [0x00331] in <1055e94092394c9a94e7dbe657c5f555>:0 
>   at Plugin.Settings.SettingsImplementation.GetValueOrDefault[T] (System.String key, T defaultValue) [0x0001c] in <1055e94092394c9a94e7dbe657c5f555>:0 
>   at HandyApp.Helpers.Settings.get_BoxColorWorkSettings () [0x00010] in /Users/enricorossini/Projects/HandyApp/HandyApp/HandyApp/HandyApp/Helpers/Settings.cs:91 
>   at HandyApp.ViewModels.AppointmentListViewModel+<LoadData>c__async0.MoveNext () [0x00154] in /Users/enricorossini/Projects/HandyApp/HandyApp/HandyApp/HandyApp/ViewModels/AppointmentListViewModel.cs:44 
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
>   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018 
>   at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:18 
>   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
>   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Java.Lang.IRunnable.cs:81 
>   at (wrapper dynamic-method) System.Object:ec7cfaa4-bbaf-45f5-baea-e4a9c61b10f1 (intptr,intptr)

**Comment by jamesmontemagno** [comment]
Color is not supported. Please see list of supported values. You should save the string hex and covert to and from:

```csharp

private const string BoxColorWorkKey = "BoxColorWork_key";
private static readonly string BoxColorWorkDefault = "#65A4BE";
public static Color BoxColorWorkSettings
{
 get
    {
        var color = AppSettings.GetValueOrDefault<string>(BoxColorWorkKey, BoxColorWorkDefault);
        return Color.FromHex(color);
    }
    set
    {
       var color = value;
             int red = (int) (color.R * 255);
        int green = (int) (color.G * 255);
        int blue = (int) (color.B * 255);
        int alpha = (int)(color.A * 255);
        string hex = String.Format("#{0:X2}{1:X2}{2:X2}{3:X2}", red, green, blue, alpha);
        AppSettings.AddOrUpdateValue<string>(BoxColorWorkKey, hex);
    }
}

```
