### ISSUE TITLE
[Feature Request] Support for iOS App Groups

### ISSUE THREAD

**Issue by elneilios** [jamesmontemagno/SettingsPlugin#49]
## Feature Request:
It would be nice if we could store the Settings in the NSUserDefaults within an App Group (so the settings can be shared with iOS extensions)

**Comment by jamesmontemagno** [comment]
This is in the 2.6.0 beta today :)

**Comment by elneilios** [comment]
Do you have an example of how I can set things up to use an App Group?
Thanks,Neil  





On Tue, Feb 21, 2017 5:02 PM, James Montemagno notifications@github.com  wrote:
This is in the 2.6.0 beta today :)

**Comment by jamesmontemagno** [comment]
Each method takes in the group's name at the end :)

This way you can do it for each individual setting.
