### ISSUE TITLE
Binding with PRISM Framework

### ISSUE THREAD

**Issue by riandesign** [jamesmontemagno/SettingsPlugin#52]
With Prism Framework, I create a binding property like this:

```
private static User _loggedUser;
public User LoggedUser {
    get { return _loggedUser; }
    set { SetProperty(ref _loggedUser, value); }
}
```

How would I get the Settings.LoggedUser value and pass to that binding property?
What's the best way to work in this case?

**Comment by jamesmontemagno** [comment]
Read the readme
