### ISSUE TITLE
[Question] How is this plugin different from/better than App.Current.Properties?

### ISSUE THREAD

**Issue by dgerding** [jamesmontemagno/SettingsPlugin#56]
Sorry if this is the wrong place to ask, but I'm not clear on the intended differences between this and the Xamarin Properties bits?

Thanks,
Dave G

**Comment by jamesmontemagno** [comment]
This plugin saves [specific properties](https://github.com/jamesmontemagno/SettingsPlugin#data-types-supported) directly to each platforms native settings APIs (NSUserDefaults, SharedPreferences, etc). This ensures the fastest, most secure, and reliable creation and editing settings per application. Additionally, it works with any Xamarin application, not just Xamarin.Forms.

App.Current.Properties actually serializes and deserializes items to disk as per implementations such as: https://github.com/xamarin/Xamarin.Forms/blob/e6d5186c8acbf37b877c7ca3c77a378352a3743d/Xamarin.Forms.Platform.iOS/Deserializer.cs

To me that isn't as reliable as saving direct to the native platforms settings.
