### ISSUE TITLE
Comparison to Xamarin.Forms.Application.Properties

### ISSUE THREAD

**Issue by breyed** [jamesmontemagno/SettingsPlugin#57]
How does this package compare to the functionality in Xamarin.Forms.Application.Properties?

Some write-up in the readme would be helpful, since the readme implies this package is useful with Xamarin Forms, and yet there seems to be considerable overlap between this package and what's build into Xamarin Forms.

**Comment by jamesmontemagno** [comment]
See: https://github.com/jamesmontemagno/SettingsPlugin/issues/56
