### ISSUE TITLE
How to store setting is an Object?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [jamesmontemagno/SettingsPlugin#58]
I have an Object HUMAN: EyesColor, HairColor, Name, Tall
How to store setting is HUMAN Object or I must create one by one properties of HUMAN?

**Comment by jamesmontemagno** [comment]
Settings are for simple properties, not full structures. You could save it into a string via json if you needed too, however not recommended.

If you need to store a lot of data, you should create a database: https://github.com/praeclarum/sqlite-net
