### ISSUE TITLE
Would be nice to have a clear all settings method in CrossSettings

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/SettingsPlugin#6]
_From @bmmathe on April 8, 2016 18:4_

Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [ ] Bug
- [x ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [x ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.1.0

For debugging purposes it would be nice to have a way to clear all settings in the CrossSettings.Current object.  It would also be helpful in a "Delete Profile" scenario.

_Copied from original issue: jamesmontemagno/Xamarin.Plugins#274_

**Comment by jamesmontemagno** [comment]
_From @Korayem on May 9, 2016 21:13_

I would say this is utterly important, not just in Debugging because for apps with authentication, we must clear all cache upon user's logout to ensure next user who'll login won't see any old cached data.

It can be done now through a foreach on list of cache keys, but a big "CLEAR'EM ALL" panic button will be lovely :)

**Comment by Korayem** [comment]
@jamesmontemagno exactly my point :)

The thing is, I don't see any way to loop through existing cache keys :(
![image](https://cloud.githubusercontent.com/assets/198332/16542505/551b2a96-40ab-11e6-8495-10487ececc85.png)

**Comment by jamesmontemagno** [comment]
@Korayem Checkout: https://www.nuget.org/packages/Xam.Plugins.Settings/2.5.0-beta4
