### ISSUE TITLE
Store and retrive a  List<string> in settings 

### ISSUE THREAD

**Issue by jamal-deen-EB** [jamesmontemagno/SettingsPlugin#61]
In my project I would like to show the `List<string>` even after `killing(close) `the App. I am using the below code for persistent list values.
```
private const string EmailKey = "emails_key";
        private static readonly List<string> EmailListDefault = new List<string>();

        	public static List<string> EmailList
		{			
			get
			{
				return AppSettings.GetValueOrDefault<List<string>>(EmailKey, EmailListDefault);
			}
			set
			{				
				AppSettings.AddOrUpdateValue<List<string>>(EmailKey, value);
			}
		
		}
```
This `list` values are getting `reset `once we kill the app and open it again. however I can get the values for `string` and `bool` even after killing the app.

**plugin version** - 2.5.4
**Platform** - iOS
Tested on both `Simulator` and `Device`.

I would like to get the `List` values even after killing the App. is there any possibility to retrieve the already saved` List.`

**Comment by jamesmontemagno** [comment]
This is not supported and will not be. I only support what I have listed for specific types. You could always serialize the string out.
