### ISSUE TITLE
How exactly is this supposed to be used?

### ISSUE THREAD

**Issue by silverfox1948** [jamesmontemagno/SettingsPlugin#64]
# Bug 
I've tried several different ways to get this to work. I have a PCL project, and one Android project at the moment. 

I've added this package to my PCL project, and to my Android project. I've added some custom settings in the PCL version of the Settings.cs file. However, every attempt to actually set a value throws an exception that states that the capability  is not implemented. 

Looking at the source in this project, I see:
```
static ISettings CreateSettings()
        {
#if PORTABLE
            return null;
#else
            return new SettingsImplementation();
#endif
        }
        internal static Exception NotImplementedInReferenceAssembly()
        {
            return new NotImplementedException("This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.");
        }
    }
```  
The exception message has: "You should reference the NuGet package from your main application project in order to reference the platform-specific implementation".

I do indeed have that. It just appears that the code is deliberately NOT implementing the capability to set a setting in the PCL version. Not sure why.

I've tried adding the custom settings to the Android version (and taking them out of the PCL version, and fixing up my references in the Android project - still no joy.

So, how exactly is this supposed to be referenced in each project, and in which of potentially many settings.cs files should I be implementing my custom settings?

Further explanation would be greatly appreciated. I've looked at the coffee-cup app, and as far as I can tell, I'm implementing Settings.cs the same way, but with remarkably little success.

**Comment by jamesmontemagno** [comment]
You need to install them into both projects, maybe try uninstalling/re-installing the nugets + a full clean and re-build. probably just a build issues in VS/XS.
