### ISSUE TITLE
what is the use of AppSettings.GetValueOrDefault<string>(UserNameKey, UserNameDefault);

### ISSUE THREAD

**Issue by hemakumarveerla** [jamesmontemagno/SettingsPlugin#69]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin:
Device Tested On: nexus
Simulator Tested On: nexus

## Feature Request:
Please fill in what you would like

**Comment by jamesmontemagno** [comment]
This would get a username from your saved preferences. Please read through the Readme file.
