### ISSUE TITLE
Plugin.Settings.rd.xml not found

### ISSUE THREAD

**Issue by doodz** [jamesmontemagno/SettingsPlugin#73]
hi,
on UWP I have an error on compile with nuget 3.0.0.64-beta :

"Le fichier de charge utile 'C:\Users\Ividata7\.nuget\packages\Xam.Plugins.Settings\3.0.0.64-beta\lib\UAP10\Plugin.Settings\Properties\Plugin.Settings.rd.xml' n'existe pas.	ApptestSsh.UWP"

**Comment by jamesmontemagno** [comment]
Try 3.0.0.66-beta
