### ISSUE TITLE
Potential different .NET 4.5 apps can override/damage settings of each other

### ISSUE THREAD

**Issue by netsrotr** [jamesmontemagno/SettingsPlugin#74]
Within the settings implementation of "src/Plugin.Settings.Net45/Settings.cs" you use the framework function "IsolatedStorageFile.GetUserStoreForAssembly()" to get the isolated storage settings target. According to the [.NET docs](https://msdn.microsoft.com/en-us/library/system.io.isolatedstorage.isolatedstoragefile.getuserstoreforassembly(v=vs.110).aspx) this may cause issues because if one use your .NET implementation assembly within different applications will always uses the same isolated store when using this method (see remarks section).
Maybe it is better to use the call [.GetUserStoreForDomain()](https://msdn.microsoft.com/en-us/library/system.io.isolatedstorage.isolatedstoragefile.getuserstorefordomain(v=vs.110).aspx) to separate settings of different apps using the same (your) impl. assembly.

What do you think?

**Comment by jamesmontemagno** [comment]
Are you sure? 

It says: Different assemblies running within the same application domain always have distinct isolated stores.

always have distinct... @Clancey implemented it

**Comment by netsrotr** [comment]
Yes, different assemblies. But if one use -> **your** <- implementation (dll/assembly) in different apps it is always the same assembly: -> **your** <- assembly implementing the Store access. If -> **I am** <- call the method at Store in different assemblies, I will have distinct stores, yes.

**Comment by Clancey** [comment]
Yes, you seem correct.  You should send a pull request changing it to GetUserStoreForApplication Method ()

**Comment by jamesmontemagno** [comment]
Ahhhh interesting :) good one, the wording is very strange on there :) will change in the next v3 change.
