### ISSUE TITLE
How to create custom keys at runtime?

### ISSUE THREAD

**Issue by goldmont** [jamesmontemagno/SettingsPlugin#75]
Hi,

Does your plugin only work with `const` strings? In order to create at runtime custom keys made by letters only, I need to declare strings as `static readonly` but your plugin returns always an empty string. Instead, declaring strings as constants, it works fine. How to solve? Thanks.

**Comment by jamesmontemagno** [comment]
Any string you want!

**Comment by jamesmontemagno** [comment]
See: https://github.com/xamarinhq/app-evolve/blob/master/src/XamarinEvolve.DataStore.Mock/Helpers/Settings.cs#L39
