### ISSUE TITLE
Opt in to (re)generating Settings.cs when updating Nuget

### ISSUE THREAD

**Issue by roycornelissen** [jamesmontemagno/SettingsPlugin#78]
I just updated a large solution with the latest version of the Settings plugin. Not every project in that solution has a Settings.cs. During the update, the Nuget package added the boilerplate Settings.cs file to each of these projects, which I then have to remove manually.

Is there a way to opt in to generating this file? I get asked whether I want to overwrite any existing Settings.cs, so that's great, but I wouldn't like a new Settings.cs to be generated with each Nuget update.

**Comment by jamesmontemagno** [comment]
Unfortunately there isn't. It is kinda legacy at this point. If I remove it, then it will be removed from all projects if. People upgrade :(. My recommendation is to not delete the file, but just the contents.

**Comment by jamesmontemagno** [comment]
Others want the ability to not generate on update too, but doesn't seem possible, I tried to remove it, but would break every app since it removed it :( https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations

**Comment by roycornelissen** [comment]
Thanks! I guess we'll have to live with it then :)

**Comment by jamesmontemagno** [comment]
Yeah, it is not super ideal and I take it back now adding it in so many years ago :(
