### ISSUE TITLE
Convert default Settings.cs from NUGET package to a README

### ISSUE THREAD

**Issue by tuyen-vuduc** [jamesmontemagno/SettingsPlugin#84]
Hi,

Thank you for your library. It works great.

However, I got frustrated when update the package when a new Settings.cs file is always generated.

Could you plz remove it from the package or convert it to a readme?

Regards.

**Comment by jamesmontemagno** [comment]
See this thread: https://github.com/jamesmontemagno/SettingsPlugin/issues/78


Recommendation is not to delete the file, but just clear it out.
