### ISSUE TITLE
The UWP version has very small storage size.

### ISSUE THREAD

**Issue by amalsher** [jamesmontemagno/SettingsPlugin#87]
I'm using this plugin for storing quite big amount of data that I get from backend for offline usage.
It works perfectly well on Android and iOS, but when I try to use it in UWP project, I get the following error:
  "WinRT information: Error trying to write application data container value
  The size of the state manager setting value has exceeded the limit."
It would be nice if the UWP version implemented a different solution and would allow to store bigger amounts of data.

**Comment by jamesmontemagno** [comment]
What type of data are you storing? You should be storing very small things like strings, bools, and ints.
