### ISSUE TITLE
Problem with running the sample project

### ISSUE THREAD

**Issue by Afshin1980** [jamesmontemagno/SettingsPlugin#88]
**Failure to fill out this information will result in this issue being closed.**
Hello 
when i try to run the sample project in visual studio 2017 i get this error

Error	CS0006	Metadata file 'D:\SettingsPlugin-master\samples\SettingsSample\SettingsSample\bin\Debug\SettingsSample.dll' could not be found		Active

## Bug Information

Version Number of Plugin: 3.0.1.0
Device Tested On: Visual Studio
Simulator Tested On:Visual Studio
Version of VS: 2017

**Comment by jamesmontemagno** [comment]
Couldn't reproduce and you didn't fill in enough information about what project you were even trying to run. I can only assume you didn't restore nugets.
