### ISSUE TITLE
Feature Request: Support for nullable (value) types required.

### ISSUE THREAD

**Issue by nbaua** [jamesmontemagno/SettingsPlugin#90]
Hi,

Thanks for the awesome plug-in, I want to propose a new feature request with the SettingsPlugin.

Since this plug-in supports really good variety of data-types it makes more sense to include support for the null-able types.

For example: int? or long? would make it more flexible while storing values.
Also I would love to have DateTime? in the plug-in as well.

I assume this ain't a major request, however please consider implementing the same at earliest.

Thanks
N Baua

**Comment by jamesmontemagno** [comment]
Nullables wont be supported, however you can remove the setting and then check to see if it exists.
