### ISSUE TITLE
Feature, iOS: Custom Defaults Name

### ISSUE THREAD

**Issue by kspearrin** [jamesmontemagno/SettingsPlugin#92]
Any chance of having an option on iOS added so that we can specify the default `NSUserDefaults` name? For example, if sharing settings with an app extension through a group this has to be set to the group name.

I see in v3.0.0 you added the ability to pass a `fileName` which can be done on a per call basis, but it would be nice to specify it during start up and forget about it.

For now I have to roll my own custom implementation of `ISettings` on iOS to get this behavior.

See:

- https://github.com/bitwarden/mobile/blob/master/src/iOS/AppDelegate.cs#L293
- https://github.com/bitwarden/mobile/blob/master/src/iOS.Core/Services/Settings.cs#L14

Thanks.

**Comment by jamesmontemagno** [comment]
No plans on implementing this as it is already there, just always pass in the fileName. The default is standard NSUserDefaults.
