### ISSUE TITLE
NSPhotoLibraryUsageDescription issue uploading to iTunes Connect. Caused by SettingsPlugin?

### ISSUE THREAD

**Issue by ghost** [jamesmontemagno/SettingsPlugin#94]
Version Number of Plugin: 2.5.1.0

When I upload to iTunes Connect, I'm getting an issue:

> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data. 

I'm trying to determine which package/plugin is triggering the issue, as I am not accessing any private folders in my code.

Could the SettingsPlugin be accessing 'private' folders and thus triggering this  #issue?

**Comment by prashantvc** [comment]
The `NSPhotoLibraryUsageDescription` specifically needed when developer wants to access the photo library([docs here](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW17)). The settings plugin in no way tries to access the photo library. 

Are there any other third party libraries in you app? Did you try verify the archive without Settings plugin added to your project?

**Comment by ghost** [comment]
Thanks - I doubted that the Settings plugin did access the photo library.

Verifying without the Settings plugin is hard, because removing the Plugin will cause code to break.

It appears from other discussons on various forums that this issue can be triggered from static analysi of the libraries/packages included in the app, if any of them refer to UIPicker (for example).

So fo now I've just had to include the NSPhotoLibraryUsageDescription info.plist entry, because it's virtually impossible to find out which library is triggering this!

**Comment by jamesmontemagno** [comment]
It is not this plugin. It could be permissions plugin or the media plugin or third party libraries actually.

Basically just add the permission and move on is what I do :)

**Comment by ghost** [comment]
Thanks James - that's what I've ended up doing, just adding the info.plist entry.

It's disconcerting to have to explain to the customer that "Apple thinks the app accesses the user's photos but we don't know why."!

Sent from my Android phone using TouchDown (www.symantec.com)

-----Original Message-----
