### ISSUE TITLE
Handling enums

### ISSUE THREAD

**Issue by tofutim** [jamesmontemagno/SettingsPlugin#95]
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: Mac
Simulator Tested On: n/a
Version of VS: 7.2 build 583
Version of Xamarin: 3.8.0.26 (Mac)
Versions of other things you are using: ?

### Steps to reproduce the Behavior
Create an enum, e.g.,
```
    public enum ScanModes
    {
        Live,
        Highlight,
        Clipboard,
        Off
    }
```
try to setup Settings
```
        public static ScanModes ScanMode
        {
            get => AppSettings.GetValueOrDefault(nameof(ScanMode), ScanModes.Off);
            set => AppSettings.AddOrUpdateValue(nameof(ScanMode), value);
        }
```

### Expected Behavior
Since enums are ints... maybe, should it just work?

### Actual Behavior
Can't compile

### Screenshots
![image](https://user-images.githubusercontent.com/157766/30617604-b0dafd40-9d4b-11e7-80c8-a81b5c9cb6a2.png)

![image](https://user-images.githubusercontent.com/157766/30617579-92096f00-9d4b-11e7-8811-984ced77f05b.png)

**Comment by jamesmontemagno** [comment]
you could cast them as an Int

You should set them to specific number though in your enum so they don't get changed in the future.

**Comment by tofutim** [comment]
looks like in your WinPhone example you use string and then Enum.Parse it...

**Comment by jamesmontemagno** [comment]
Yeah, either way would work.

**Comment by jamesmontemagno** [comment]
I will leave this in the developers hands on how they want to parse it in and out.

**Comment by tofutim** [comment]
how would you feel about:
```
    public static class ISettingsExt
    {
        public static TEnum GetEnumValueOrDefault<TEnum>(this ISettings settings, TEnum defaultValue)
            where TEnum : struct
        {
            TEnum result = default(TEnum);
            bool enumParseResult = false;

            var strTarget = settings.GetValueOrDefault(nameof(TEnum), defaultValue.ToString());
            enumParseResult = Enum.TryParse(strTarget, true, out result);
            return result;
        }

        public static bool AddOrUpdateEnumValue<TEnum>(this ISettings settings, TEnum value, string fileName = null)
        {
            return settings.AddOrUpdateValue(nameof(TEnum), value.ToString(), fileName);
        }
    }
```
which lets me
```
        public static ScanModes ScanMode
        {
            get => AppSettings.GetEnumValueOrDefault<ScanModes>(ScanModes.Off);
            set => AppSettings.AddOrUpdateEnumValue<ScanModes>(value);
        }
```
but yeah, enum is fraught with issues... so maybe dev can decide on implementation. Is the more fundamental value the text? or is it the value?
