### ISSUE TITLE
Support to updated settings plugin

### ISSUE THREAD

**Issue by mhdshbk** [jamesmontemagno/SettingsPlugin#97]
I'm getting such an error!
<img width="519" alt="screen shot 2017-09-26 at 12 32 15 pm" src="https://user-images.githubusercontent.com/14141789/30846906-0dbd804e-a2b7-11e7-91f4-b2f1eb078efb.png">

**Comment by prashantvc** [comment]
@mhdshbk Could you elaborate the issues? Please share following information

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior

### Expected Behavior

### Actual Behavior

### Code snippet

**Comment by mhdshbk** [comment]
Version Number of Plugin: 3.0.1
Device Tested On: NIL
Simulator Tested On: iPhone 7 iOS 11
Version of VS: VS for Mac 7.1.5(Build 2)
Version of Xamarin: Xamarin.iOS 11.0.0.0
Versions of other things you are using: Nothing else

**Comment by Jerome2606** [comment]
I use the AddOrUpdate with serialized data as string:

` AddOrUpdateValue(Constants.UserProfileKey, JsonConvert.SerializeObject(userProfile)));`

And then to getValue, deserialize the object:

```
var profile = GetValue<string>(Constants.UserProfileKey);
if (profile != null)
{
    JsonSerializerSettings settings = new JsonSerializerSettings()
    {
        NullValueHandling = NullValueHandling.Ignore,
        MissingMemberHandling = MissingMemberHandling.Ignore

    };
    userInfoModel = JsonConvert.DeserializeObject<UserInfoModel>(profile, settings);
}
```

**Comment by jamesmontemagno** [comment]
Closing this as yes the API was changed to not allow generics as they are not supported. Make sure all your NuGets are up to date.

**Comment by mhdshbk** [comment]
@jamesmontemagno Solved that issue :)
