### ISSUE TITLE
Misspelling on Getting Started Page

### ISSUE THREAD

**Issue by akadooie** [jamesmontemagno/SettingsPlugin#99]
Hi,

Just wanted to let you know about some misspelled words on the getting started Page. In the "Removing Settings" section there is the following line "**publc** static void RemoveUserName() => AppSettings.Remove(nameof(UserName));". 

Here is the link to the page, https://jamesmontemagno.github.io/SettingsPlugin/RemoveSettings.html 

Not really a problem, just wanted to let you know. Cheers!

**Comment by jamesmontemagno** [comment]
Send a PR
